# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='apply time'),
        ),
    ]
