# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20160419_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='display_name',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 9, 39, 29, 245643), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 8, 39, 29, 244643), verbose_name='start time'),
        ),
    ]
